
#账本的种子；一段16进制字符，最长可以包含64个字符；可以用字符“-”分隔，以便更容易读取；
ledger.seed=932dfe23-fe23232f-283f32fa-dd32aa76-8322ca2f-56236cda-7136b322-cb323ffe

#账本的描述名称；此属性不参与共识，仅仅在当前参与方的本地节点用于描述用途；
ledger.name=

#参与方的个数，后续以 cons_parti.id 分别标识每一个参与方的配置；
cons_parti.count=4

#第0个参与方的名称；
cons_parti.0.name=jd.com
#第0个参与方的公钥文件路径；
cons_parti.0.pubkey-path=keys/jd-com.pub
#第0个参与方的公钥内容（由keygen工具生成）；此参数优先于 pubkey-path 参数；
cons_parti.0.pubkey=3snPdw7i7PapsDoW185c3kfK6p8s6SwiJAdEUzgnfeuUox12nxgzXu
#第0个参与方的共识服务的主机地址；
cons_parti.0.consensus.host=127.0.0.1
#第0个参与方的共识服务的端口；
cons_parti.0.consensus.port=8900
#第0个参与方的共识服务是否开启安全连接；
cons_parti.0.consensus.secure=true
#第0个参与方的账本初始服务的主机；
cons_parti.0.initializer.host=127.0.0.1
#第0个参与方的账本初始服务的端口；
cons_parti.0.initializer.port=8800
#第0个参与方的账本初始服务是否开启安全连接；
cons_parti.0.initializer.secure=true

#第1个参与方的名称；
cons_parti.1.name=at.com
#第1个参与方的公钥文件路径；
cons_parti.1.pubkey-path=keys/at-com.pub
#第1个参与方的公钥内容（由keygen工具生成）；此参数优先于 pubkey-path 参数；
cons_parti.1.pubkey=3snPdw7i7Ph1SYLQt9uqVEqiuvNXjxCdGvEdN6otJsg5rbr7Aze7kf
#第1个参与方的共识服务的主机地址；
cons_parti.1.consensus.host=127.0.0.1
#第1个参与方的共识服务的端口；
cons_parti.1.consensus.port=8910
#第1个参与方的共识服务是否开启安全连接；
cons_parti.1.consensus.secure=false
#第1个参与方的账本初始服务的主机；
cons_parti.1.initializer.host=127.0.0.1
#第1个参与方的账本初始服务的端口；
cons_parti.1.initializer.port=8810
#第1个参与方的账本初始服务是否开启安全连接；
cons_parti.1.initializer.secure=false

#第2个参与方的名称；
cons_parti.2.name=bt.com
#第2个参与方的公钥文件路径；
cons_parti.2.pubkey-path=keys/bt-com.pub
#第2个参与方的公钥内容（由keygen工具生成）；此参数优先于 pubkey-path 参数；
cons_parti.2.pubkey=3snPdw7i7PezptA6dNBkotPjmKEbTkY8fmusLBnfj8Cf7eFwhWDwKr
#第2个参与方的共识服务的主机地址；
cons_parti.2.consensus.host=127.0.0.1
#第2个参与方的共识服务的端口；
cons_parti.2.consensus.port=8920
#第2个参与方的共识服务是否开启安全连接；
cons_parti.2.consensus.secure=false
#第2个参与方的账本初始服务的主机；
cons_parti.2.initializer.host=127.0.0.1
#第2个参与方的账本初始服务的端口；
cons_parti.2.initializer.port=8820
#第2个参与方的账本初始服务是否开启安全连接；
cons_parti.2.initializer.secure=true

#第3个参与方的名称；
cons_parti.3.name=xt.com
#第3个参与方的公钥文件路径；
cons_parti.3.pubkey-path=keys/xt-com.pub
#第3个参与方的公钥内容（由keygen工具生成）；此参数优先于 pubkey-path 参数；
cons_parti.3.pubkey=3snPdw7i7PerZYfRzEB61SAN9tFK4yHm9wUSRtkLSSGXHkQRbB5PkS
#第3个参与方的共识服务的主机地址；
cons_parti.3.consensus.host=127.0.0.1
#第3个参与方的共识服务的端口；
cons_parti.3.consensus.port=8930
#第3个参与方的共识服务是否开启安全连接；
cons_parti.3.consensus.secure=false
#第3个参与方的账本初始服务的主机；
cons_parti.3.initializer.host=127.0.0.1
#第3个参与方的账本初始服务的端口；
cons_parti.3.initializer.port=8830
#第3个参与方的账本初始服务是否开启安全连接；
cons_parti.3.initializer.secure=false
